### ISSUE TITLE
Scan results from non-CodeQL security scan tools do not appear on the Microsoft Defender for Cloud DevOps security scan results screen

### ISSUE THREAD

**Issue by apc-t-aoki** [microsoft/security-devops-action#118]
Only CodeQL execution results are displayed, and scan results from security scan tools such as checkov, trivy, etc. are not displayed on the Microsoft Defender for Cloud DevOps security scan results screen.I found this issue last week.

This issue gives the example of trivy, but I have seen similar events with Checkov also.

Is there a way to output the results of a security tool run other than CodeQL again?

### Issue Details

*Some information is masked for information protection.

#### GitHub Actions workflow file I'm using

```yaml
name: Build image and deploy

on:
  push:
    branches: [ main ]
    
permissions:
  contents: read
  id-token: write
  actions: read

jobs: 
  build:
    runs-on: ubuntu-latest
    name: Build & Push
    steps:
        # Checkout
      - uses: actions/checkout@v3
      
        # Azure Login
      - name: Login to Azure Public Cloud
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Container Build Dockerfile
      - name: Container image build Dockerfile
        run: |
          az acr login -n ${{ vars.ACR_NAME }}
          docker build -t ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.APP_NAME }}:latest .
             
        # Run analyzers
      - name: Run Microsoft Security DevOps for Dockerfile
        uses: microsoft/security-devops-action@latest
        with:
          tools: 'trivy'
        env:
          GDN_TRIVY_ACTION: image
          GDN_TRIVY_TARGET: ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.APP_NAME }}:latest
          GDN_TRIVY_SEVERITIES: HIGH,CRITICAL
          GDN_TRIVY_EXITCODE: 1

      - name: Push container image Dockerfile
        run: |
          docker push ${{ vars.ACR_NAME }}.azurecr.io/${{ vars.APP_NAME }}:latest
```

#### Previous security results screen:

![Image](https://github.com/user-attachments/assets/95bc6c82-0720-406c-b40c-01c3a736b471)

#### Current security result screen:

![Image](https://github.com/user-attachments/assets/507c045a-a67c-4e06-88dc-7e909788aece)

#### KQL

```
securityresources
| where type == "microsoft.security/assessments/subassessments"
| extend assessmentKey = extract(".*assessments/(.+?)/.*",1,  id)
| where assessmentKey == "6588c4d4-fbbb-4fb8-be45-7c2de7dc1b3b" or assessmentKey == "d9be0ff8-3eb0-4348-82f6-c1e735f85983"
| extend Source = tostring(properties.resourceDetails.source)
| extend Repo = tostring(iff(Source == 'GitHub', split(id,'/')[14], split(id,'/')[16])), Project = tostring(iff(Source == 'AzureDevOps', split(id,'/')[14], 'N/A')), Organization = tostring(iff(Source == 'GitHub', split(id,'/')[12], split(id,'/')[12])),
    Finding = tostring(properties.status.description),
    Status = tostring(properties.status.code),
    Severity = tostring(properties.status.severity),
    Tool = tostring(iff(Source == 'GitHub', properties.additionalData.data.Tool_name, properties.additionalData.data.ToolName)),
    RuleID = tostring(properties.additionalData.data.Rule_id),
    Branch = tostring(properties.additionalData.data.Branch),
    Details = "info"
| extend AlertUrl = tostring(iff(Source =~ "GitHub", properties.additionalData.data.Html_Url, iff(Tool =~ "CodeQL", properties.additionalData.data.Html_Url, properties.additionalData.data.Build_Url)))
| extend SeveritySort = case(
    Severity == "High", 1,
    Severity == "Medium", 2,
    Severity == "Low", 3,
    4
)
| order by SeveritySort asc, Severity asc
| project-away SeveritySort
| project Severity, Source, Organization, Project, Repo, Finding, Tool, properties, AlertUrl, Details
```
