### ISSUE TITLE
env parameters not being picked up in ADO pipeline for IaC

### ISSUE THREAD

**Issue by jmyers82** [microsoft/security-devops-action#27]
## Issue
When using the MicrosoftSecurityDevops@1 task in an ADO pipeline, I am not seeing in the logs where the env parameters being passed are being used?  I am passing a IacDir / SkipRules and both are being ignored as far as I can tell. 

## Configuration
Agent: Windows Latest
Terraform: 1.1.7

```
- task: MicrosoftSecurityDevOps@1
  displayName: 'Microsoft Defender - IaC Scan'
  inputs:
    categories: IaC
    tools: terrascan
  env:
    IacType: "terraform"
    IacDir: "$(System.DefaultWorkingDirectory)\\$(Build.Repository.Name)\\iac\\modules"
    SkipRules: "AC_AWS_0214"
```

## Error
See attached file for raw log of output.  Notice that the Target Directory is not being set and that it is still throwing errors for the rule that should be skipped. 
[iacscan.txt](https://github.com/microsoft/security-devops-action/files/9462285/iacscan.txt)

## Expected results
I am expecting the scan to ONLY scan the directory that I pass in, instead it is scanning everything in the root system.defaultworkingdirectory and ignore the rule listed in the skiprules parameter.
