### ISSUE TITLE
Missing bimskin scanning when running as default

### ISSUE THREAD

**Issue by ktran1005** [microsoft/security-devops-action#66]
Hello everyone, I am trying to use **task: MicrosoftSecurityDevOps@1** to scan through my code. I leave it as default which I assume that it will run all the tools it covers. However, when I run the pipeline, this is the tools it runs (it doesn't have binskim) . Anyone has any idea why this happened. Thanks!
![image](https://github.com/microsoft/security-devops-action/assets/88155108/6de21dd2-3ab3-4048-a18c-44012a036569)

**Comment by ktran1005** [comment]
followed up with this issue. When I use tools parameter to specify binskim then I received this error. 
 **##[error]Error running binskim job: 1 of 1
 ##[error]AnalyzeArgumentNoValuesException: Argument Target has no values. Check your configuration. -- Additional arguments:Microsoft.Guardian.InvalidResponseFileContentsException: InvalidResponseFileContentsException: Cannot create a response file with zero arguments.**

```yaml
steps:
- task: MicrosoftSecurityDevOps@1
  displayName: 'Run Microsoft Defender for DevOps'
  inputs:
    tools: 'binskim, terrascan, credscan'
```

**Comment by JiandongJiang** [comment]
Can you please check if there are any .dll and/or .exe files in the default working directory? If there is no such file, then the above error you hit is expected and the BinSkim tool is regarded as not applicable for your case/scenario, which is why the BinSkim tool was not run in the first place. Please check and let us know. Thanks.

**Comment by ktran1005** [comment]
Hi @JiandongJiang. Thanks for the response. I was using the binskim tasks earlier without no issues but wanted to switch to MicrosoftSecurityDevOps tasks. In my binskim task, I downloaded my artifact and stored it into a specific directory, and I was able to specify the path of the directory and pass it to binskim to scan (this method ran without any issues). I wonder if we have something similar to that. Below is the way that I use BinSkin task in my yaml.

```yaml
    - task: BinSkim@3
      displayName: 'Run BinSkim'
      continueOnError: true
      inputs:
        InputType: 'Basic'
        Function: 'analyze'
        AnalyzeTarget: '$(Build.ArtifactStagingDirectory)/binskim/${{ parameters.binskimPath }}'
        AnalyzeVerbose: true
        AnalyzeRecurse: true
```

**Comment by ktran1005** [comment]
updated part 3: I tried to use env variable to fix target path but had no luck too
```yaml
    - task: MicrosoftSecurityDevOps@1
      displayName: 'Microsoft Security DevOps'
      inputs:
        tools: 'binskim'
      env:
        binskim_target: '$(Build.ArtifactStagingDirectory)\binskim\${{ parameters.binskimPath }}'
```
